### ISSUE TITLE
A few cmake issues

### ISSUE THREAD

**Issue by wangvsa** [hpc-io/pdc#59]
1. "-Wimplicit-fallthrough=3" is not compatible with older gcc versions.
  - It will report this error **gcc: error: unrecognized command line option '-Wimplicit-fallthrough=3'**
2. cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/install
  - CMAKE_INSTALL_PREFIX option seems does not work, bin/lib/include are still installed in the build directory.
3. close_server binary is not built unless BUILD_TESTING is set to ON.
 - close_server and pdc_server should always be built together
 - Suggestion: use **pdc_server start** and **pdc_server close** in stead of a dedicated close_server command.
4. PDC_DISABLE_CHECKPOINT=ON does not disable checkpointing.
  - Is it better to name it PDC_ENABLE_CHECKPOINT to make it consistency with other options such as: PDC_ENABLE_APP_CLOSE_SERVER, PDC_ENABLE_FASTBIT:BOO, PDC_ENABLE_LUSTRE, etc.

**Comment by QiaoK** [comment]
Thank you for pointing these out. I have fixed all of these accordingly in the develop branch

**Comment by wangvsa** [comment]
Thank you! A small mistake in cmake file, ENABLE_CHECKPOINT should be PDC_ENABLE_CHECKPOINT

**Comment by wangvsa** [comment]
I just tested on Quartz at LLNL. The DCMAKE_INSTALL_PREFIX option seems still doesn't work.

**Comment by QiaoK** [comment]
> I just tested on Quartz at LLNL. The DCMAKE_INSTALL_PREFIX option seems still doesn't work.

I see. The PDC_ENABLE_CHECKPOINT and DCMAKE_INSTALL_PREFIX issues are fixed now.

**Comment by wangvsa** [comment]
bin directory is not installed.

**Comment by QiaoK** [comment]
> bin directory is not installed.

Now it should work.

**Comment by wangvsa** [comment]
Thanks
